### ISSUE TITLE
in local testing got No module named 'flask_cors'

### ISSUE THREAD

**Issue by raybellwaves** [fsspec/s3fs#584]
Created a dev env as

`pip install -r requirements.txt -r test_requirements.txt`
`pip install --no-deps -e .`

and ran `pytest s3fs/tests/test_s3fs.py -k test_info` and got 

```
...
>           raise EndpointConnectionError(endpoint_url=request.url, error=e)
E           botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://127.0.0.1:5555/test"

../../../miniconda3/envs/test_env/lib/python3.9/site-packages/botocore/httpsession.py:414: EndpointConnectionError
------------------------------------------------------------------------------------------- Captured stderr setup --------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ray/miniconda3/envs/test_env/bin/moto_server", line 5, in <module>
    from moto.server import main
  File "/Users/ray/miniconda3/envs/test_env/lib/python3.9/site-packages/moto/server.py", line 11, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
```

**Comment by martindurant** [comment]
Good find - should add `flask` to the test deps. Basically, it should contain the same things as the CI environment.

**Comment by raybellwaves** [comment]
> Good find - should add `flask` to the test deps. Basically, it should contain the same things as the CI environment.

It's there https://github.com/fsspec/s3fs/blob/main/test_requirements.txt#L3

**Comment by martindurant** [comment]
It is totally possible that the conda(-forge) package is more inclusive than the pypi variant.
