### ISSUE TITLE
callbacks not supported in `_get_file` and `_put_file`

### ISSUE THREAD

**Issue by ap--** [fsspec/s3fs#589]
Hello everyone,

I was playing with `fsspec.callbacks` trying to monitor the local file download when using a CachingFileSystem, and noticed that `get_file` and `put_file` in s3fs currently don't support callbacks.

```python
Traceback (most recent call last):
  File "_cache_test.py", line 70, in <module>
    cfs.get(path, fn, callback=MyCallback(flush=True))
  File "/Users/poehlmann/Environments/envs/pasu/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 402, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/Users/poehlmann/Environments/envs/pasu/lib/python3.8/site-packages/fsspec/spec.py", line 776, in get
    self.get_file(rpath, lpath, **kwargs)
  File "/Users/poehlmann/Environments/envs/pasu/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/poehlmann/Environments/envs/pasu/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    coro = func(*args, **kwargs)
TypeError: _get_file() got an unexpected keyword argument 'callback'
``` 

I'll open a PR right away to add the callback keyword argument for both `_get_file` and `_put_file`.
Let me know if I should add tests too.

Cheers,
Andreas 😃

**Comment by ap--** [comment]
Closed via: 6f844d4dfb70ad7f2397220663b907398659ccd6
