### ISSUE TITLE
Can't list files with minio

### ISSUE THREAD

**Issue by Dementiy** [fsspec/s3fs#618]
Hello.

Using the latest version of s3fs (python 3.9, Windows 10) and minio:latest I get the following error:

```python
s3 = S3FileSystem(
    anon=True,
    use_ssl=False,
    config_kwargs={
        "signature_version": "s3v4",
    },
    client_kwargs={
        "endpoint_url": "http://127.0.0.1:9000",
    },
)
print(s3.ls("s3://data"))  # the same with listdir
```

```
Traceback (most recent call last):
  File "...\lib\site-packages\botocore\parsers.py", line 486, in _parse_xml_string_to_dom
    parser.feed(xml_string)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 86

During handling of the above exception, another exception occurred:

...
  File "...\lib\site-packages\botocore\parsers.py", line 489, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 86), invalid XML received. Further retries may succeed:
ries may succeed:
b'<html><head><meta http-equiv="refresh" content="0; url=/block/page?m=icap_block&reason=14f809e3-3777-440e-9685-8dfe8cee6e4c&link=http://127.0.0.1:9000/data?list-type%3D2%26prefix%3D%26delimiter%3D%252F%26encoding-type%3Durl&ctc=%5B74%5D&ltc=%5B%5D&lwd=&template_id=34&st=cUNfO9mWWq6YHgghUdP5j1Yh7HCmiTfjj8/qr9MByDigvUwaV9MfDE6jA5BdVUM6CKmtMoFFar8TG32J5Li1qZqvHF5C7s1/N9LarBD%2BbsM%3D"></head></html>'
```

I don't understand why html is returned. If I follow the link in html then there is xml document:

```xml
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>data</Name>
  <Prefix/>
  <KeyCount>1</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <Delimiter>%252F</Delimiter>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>file.hdf5</Key>
    <LastModified>2022-04-22T13:18:49.105Z</LastModified>
    <ETag>"4392b1b5218b857a70aba4ea7c9e396b"</ETag>
    <Size>931202048</Size>
    <Owner>
      <ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID>
      <DisplayName>minio</DisplayName>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <EncodingType>url</EncodingType>
</ListBucketResult>
```

**Comment by martindurant** [comment]
Please check that you have recent versions of aiobotocore and botocore and that they are compatible with one-another. Did things work correctly with some pervious version of these or of s3fs?

I can't make much of the HTML, but it does mention "block", which may be some layout or perhaps indicates a permission thing.

I notice you have a `config_kwargs`, and I don't remember ever using that before. Since you are using anonymous, it ought not to matter.

**Comment by Dementiy** [comment]
The problem was related to the proxy server settings. Response message a little bit confused me. Thank you.
