### ISSUE TITLE
AccessDenied error when calling the ListObjectsV2 operation

### ISSUE THREAD

**Issue by baggiponte** [fsspec/s3fs#692]
Hello! I am trying to upload data to S3 using `s3fs.S3FileSystem.put()`. Here is my wrapper function:

```python
import s3fs
from s3fs import S3FileSystem

s3fs.core.logger.setLevel("DEBUG")

s3 = S3FileSystem()

def upload(self, *dirs_or_files: str) -> None:
    keys: tuple[str] = # other func to generate the keys

    for path, key in zip(dirs_or_files, keys):
        if os.path.isdir(path):
            fs.put(path, f"{key}/", recursive=True)
        fs.put(path, key)

def main()
    upload("./data")

if __name__ == '__main__':
    main()
```

Where `fs` is the instance of `s3fs.S3FileSystem`. However when I run the script I get the following error (and log):

```

[01/24/23 23:56:29] INFO     Found credentials in shared credentials file: ~/.aws/credentials                                                               credentials.py:1251
[01/24/23 23:56:30] DEBUG    Setting up s3fs instance                                                                                                               core.py:282
                    INFO     Found credentials in shared credentials file: ~/.aws/credentials                                                               credentials.py:1251
                    DEBUG    Get directory listing page for futura-aws-test-bucket/data                                                                             core.py:385
                    INFO     Downloading contents of 'data' into './data/prova/data'                                                                              bucket.py:603
                    DEBUG    Get directory listing page for data                                                                                                    core.py:385
[01/24/23 23:56:31] DEBUG    Get directory listing page for data                                                                                                    core.py:385
                    DEBUG    Get directory listing page for data                                                                                                    core.py:385
Traceback (most recent call last):
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/s3fs/core.py", line 394, in _lsdir
    for i in it:
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucabaggi/.local/share/pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lucabaggi/.local/share/pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/src/main.py", line 13, in <module>
    main()
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/src/main.py", line 10, in main
    bucket.download("data", under="./data/prova")
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/src/futura_aws/bucket.py", line 604, in download
    self._fs.get(key, f"{local}/", recursive=True)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 885, in get
    rpaths = self.expand_path(rpath, recursive=recursive)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 989, in expand_path
    out = self.expand_path([path], recursive, maxdepth)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 1009, in expand_path
    if p not in out and (recursive is False or self.exists(p)):
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/s3fs/core.py", line 498, in exists
    self.ls(path)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/s3fs/core.py", line 619, in ls
    files = self._ls(path, refresh=refresh)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/s3fs/core.py", line 487, in _ls
    return self._lsdir(path, refresh)
  File "/Users/lucabaggi/Documents/dev/futura/futura-aws/.venv/lib/python3.9/site-packages/s3fs/core.py", line 409, in _lsdir
    raise translate_boto_error(e)
PermissionError: Access Denied
```

The error arises when I am trying to upload a single file too.

I am using `s3fs==0.4.2` (chosen by the dependency manager).

**Comment by baggiponte** [comment]
Problem solved, I did not prefix the bucket name to the `rpath`.
