### ISSUE TITLE
S3FileSystem.ls() returns empty list

### ISSUE THREAD

**Issue by aayuhs899** [fsspec/s3fs#755]
I have the following code snippet running on a docker container:
```
from s3fs.core import S3FileSystem
s3 = S3FileSystem(cache_regions=True, client_kwargs={"region_name": "us-east-1"})
s3.ls('s3://test-bucket-20230713')
```
The output returns an empty list:
```
[]
```

The same operation using `boto3`'s `list_objects_v2`:
```
import boto3
s3_client = boto3.client('s3')
s3_client.list_objects_v2(Bucket='test-bucket-20230713')
```
Output:
```
{'ResponseMetadata': {'RequestId': '3D8YDRA8Q7D5KZ7K', 'HostId': 'B+xVJiRz4NqiJjmd0yFSEwXgWEwfVOkPYZNQ6WDE2VIFjXEm1TIkLZU6jaG/NRJxAmiU1bvKNBw=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'B+xVJiRz4NqiJjmd0yFSEwXgWEwfVOkPYZNQ6WDE2VIFjXEm1TIkLZU6jaG/NRJxAmiU1bvKNBw=', 'x-amz-request-id': '3D8YDRA8Q7D5KZ7K', 'date': 'Thu, 13 Jul 2023 19:12:50 GMT', 'x-amz-bucket-region': 'us-east-1', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'data/test_old.txt', 'LastModified': datetime.datetime(2023, 7, 13, 18, 53, 26, tzinfo=tzlocal()), 'ETag': '"7a1ff55a2596e4d015683d012c9cc7ca"', 'Size': 0, 'StorageClass': 'STANDARD'}], 'Name': 'test-bucket-20230713', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 1}
```

I have also attached the full debug log for the first command: [debug_log.txt](https://github.com/fsspec/s3fs/files/12043741/debug_log.txt)

The versions of related libraries being used here are:
```
Python: 3.8,
aiobotocore: 2.4.2,
aiohttp: 3.7.4,
fsspec: 2023.4.0, 
boto3: 1.28.2, 
botocore: 1.31.2,
s3fs: 2023.6.0
```

**Comment by martindurant** [comment]
Do the cache_regions and client_kwargs arguments make a difference?

**Comment by aayuhs899** [comment]
No, they don't. Here's the output with those omitted:
```
from s3fs.core import S3FileSystem
s3 = S3FileSystem()
s3.ls('s3://test-bucket-20230713')
```

Output:
```
[]
```

**Comment by aayuhs899** [comment]
Another data point, I tried the `touch()` method to create a new file, and looks like this is a permissions issue:
```
from s3fs.core import S3FileSystem
s3 = S3FileSystem()
s3.touch('s3://test-bucket-20230713/data/test_2.bin')
```

Output:
```
An error was encountered:
Access Denied
Traceback (most recent call last):
  File "/custom_libs/lib/python3.8/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/custom_libs/lib/python3.8/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/custom_libs/lib/python3.8/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/custom_libs/lib/python3.8/site-packages/s3fs/core.py", line 1040, in _touch
    write_result = await self._call_s3(
  File "/custom_libs/lib/python3.8/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
  File "/custom_libs/lib/python3.8/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err
PermissionError: Access Denied
```

Similar command works with `boto3`:
```
import boto3
s3_client = boto3.client('s3')
bucket='test-bucket-20230713'
key='data/test_2.bin'
data = b'\x01'*1024
s3_client.put_object(Bucket=bucket,Key=key,Body=data)
```
Output:
```
{'ResponseMetadata': {'RequestId': 'Y4RPY7MRAJBAC8NY', 'HostId': 'DiWNhaYsAQXFb/9E1nnQeK9XpmHAJ6FO9AwdvfU164oI3c4oxvz70Jc5ArOgVfUzWFV+LpEi47g=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'DiWNhaYsAQXFb/9E1nnQeK9XpmHAJ6FO9AwdvfU164oI3c4oxvz70Jc5ArOgVfUzWFV+LpEi47g=', 'x-amz-request-id': 'Y4RPY7MRAJBAC8NY', 'date': 'Thu, 13 Jul 2023 20:21:58 GMT', 'x-amz-server-side-encryption': 'aws:kms', 'x-amz-server-side-encryption-aws-kms-key-id': 'arn:aws:kms:us-east-1:721312301042:key/66a47242-12dc-4202-8ebe-6bc4794504c1', 'etag': '"e98a3e683a5fb991a3aecb5f42bb70cd"', 'server': 'AmazonS3', 'content-length': '0'}, 'RetryAttempts': 0}, 'ETag': '"e98a3e683a5fb991a3aecb5f42bb70cd"', 'ServerSideEncryption': 'aws:kms', 'SSEKMSKeyId': 'arn:aws:kms:us-east-1:721312301042:key/66a47242-12dc-4202-8ebe-6bc4794504c1'}
```

**Comment by aayuhs899** [comment]
Also tried to manually provide the same credentials used by `boto3`, since `boto3` commands seem to be working, but that did not work:
```
import boto3
from s3fs.core import S3FileSystem

session = boto3.Session()
frozen_credentials = session.get_credentials().get_frozen_credentials()

s3 = S3FileSystem(key=frozen_credentials.access_key, secret=frozen_credentials.secret_key, token=frozen_credentials.token)
s3.ls('s3://test-bucket-20230713')
```

Output:
```
[]
```

**Comment by martindurant** [comment]
I cannot see anything obviously wrong with what you are doing. If s3fs's logging and exceptions are not giving much information, you may have to make  breakpoint in _error_wrapper at func(*args, **kwargs) to see the state of what is being sent and any extra information in the exception object.

It is also, separately, worth trying with aiobotocore, to see if it does something differently that boto3 and the problem lies there.

**Comment by aayushgupta899** [comment]
Looks like it might be something to do with `aiobotocore`. Tried running the following and got an empty response:
```
import asyncio
import aiobotocore
from aiobotocore.session import get_session

BUCKET_NAME = "test-bucket-20230713"

async def list_objects():
    session = get_session()

    async with session.create_client('s3', region_name='us-east-1') as client:
        response = await client.list_objects_v2(Bucket=BUCKET_NAME)
        print(response)

        for obj in response.get('Contents', []):
            print(obj['Key'])

loop = asyncio.get_event_loop()
loop.run_until_complete(list_objects())
```

Output:
```
{'ResponseMetadata': {'RequestId': 'VDKX6MEJ9QT7T2PQ', 'HostId': 'iO41VeSb4cCY7c+5nNaWNpIw1icPX9eWY5WP0f4xsz7wODdXPKCj8hOq7mPhZrE90hvHvYgYUgU=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'iO41VeSb4cCY7c+5nNaWNpIw1icPX9eWY5WP0f4xsz7wODdXPKCj8hOq7mPhZrE90hvHvYgYUgU=', 'x-amz-request-id': 'VDKX6MEJ9QT7T2PQ', 'date': 'Fri, 14 Jul 2023 22:05:07 GMT', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}}
```

**Comment by martindurant** [comment]
Can you please file an issue with aiobotocore, in that case, and reference here?

(btw., the last two lines could be done with `asyncio.run()`, interacting directly with loops is discouraged these days)

**Comment by aayushgupta899** [comment]
Thanks Martin, I have opened an issue in `aiobotocore`: https://github.com/aio-libs/aiobotocore/issues/1024

**Comment by aayushgupta899** [comment]
This started working after I upgraded to `aiobotocore==2.5.0`. Not sure what changed though. Here are my pip freeze results:

```
aiobotocore==2.5.0
aiohttp==3.8.5
aioitertools==0.5.1
aiosignal==1.2.0
amzn-pyodin==1.2
async-timeout==4.0.2
attrs==23.1.0
boto3==1.28.65
botocore==1.31.65
charset-normalizer==3.0.0
docutils==0.15.2
frozenlist==1.3.3
fsspec==2022.2.0
gitdb==0.6.4
GitPython==2.1.8
hnswlib==0.3.4
idna==3.2
importlib-metadata==4.6.1
jmespath==0.9.5
joblib==1.2.0
multidict==6.0.4
numpy==1.18.4
pandas==1.1.3
patsy==0.5.1
pip==21.0.1
pybind11==2.3.0
PyGreSQL==5.0.7
python-dateutil==2.8.2
pytz==2023.3
s3fs==2022.2.0
s3transfer==0.7.0
scikit-learn==0.22
scipy==1.3.1
setuptools==57.4.0
six==1.16.0
sklearn==0.0
smmap==0.9.0
statsmodels==0.11.1
toml==0.10.2
tqdm==4.64.0
typing-extensions==4.1.1
urllib3==1.26.13
wrapt==1.15.0
yarl==1.8.2
zipp==3.15.0
```

**Comment by aayuhs899** [comment]
Closing this as this is no longer an issue. Please let me know if any more details are required!
