### ISSUE TITLE
Async feature is broken

### ISSUE THREAD

**Issue by dominictarro** [fsspec/s3fs#759]
Tried using the `asynchronous` feature of `S3FileSystem`, but it fails stating that there is no running loop.

```py
async def test():
  loop = asyncio.get_event_loop()
  fs = s3fs.S3FileSystem(asynchronous=True, loop=loop)
  s3 = await fs.set_session()
  # Loop should be fine
  print(loop.is_running())
  
  # Throws error shown below
  try:
      await fs.ls(path)
  except Exception as e:
    # Loop is running fine
    print(loop.is_running())
    raise e

  # Doesn't make it here
  await s3.close()
  print(loop.is_running())
```

Error traceback

```
True
True
Traceback (most recent call last):
  File "/Users/dominictarro/Documents/GitHub/Borderlands/lambdas/endpoints/dataset.py", line 36, in <module>
    loop = asyncio.run(get(event, None))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/dominictarro/Documents/GitHub/Borderlands/lambdas/endpoints/dataset.py", line 21, in get
    await fs.ls(path)
          ^^^^^^^^^^^
  File "/Users/dominictarro/.local/share/virtualenvs/Borderlands-A8IGjfOS/lib/python3.11/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominictarro/.local/share/virtualenvs/Borderlands-A8IGjfOS/lib/python3.11/site-packages/fsspec/asyn.py", line 71, in sync
    raise RuntimeError("Loop is not running")
RuntimeError: Loop is not running
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10fbb7d10>
```

**Comment by dominictarro** [comment]
Actually, misunderstood the point about [`_` prefix](https://s3fs.readthedocs.io/en/latest/index.html?highlight=async#async) in the docs.
