### ISSUE TITLE
Runtime Error: Loop is not running

### ISSUE THREAD

**Issue by vedantroy** [fsspec/s3fs#768]
Versions:
```
fsspec                        2023.6.0
s3fs                          2023.6.0
```

I'm trying to use a basic method `.get`, inside of a fast API route. Like this:

```
@app.post("/run_job")
async def run_job(payload: JobPayload):
    metadata = payload.metadata
    job_id, job_type, creds = metadata.job_id, metadata.job_type, metadata.s3_creds

    job_dir = get_job_dir(job_id)
    job_dir.mkdir()

    import asyncio

    s3 = S3FileSystem(
        key=creds.access_key,
        secret=creds.secret_key,
        client_kwargs={"endpoint_url": creds.endpoint, "region_name": creds.region},
        asynchronous=True,
        loop=asyncio.get_event_loop(),
    )
    session = await s3.set_session()
    await s3._get(some_value.rstrip('/') + "/", local_path, recursive=True)

    await session.close()
```

This does not work, but using `aiobotocore` directly does. What am I doing wrong?

**Comment by martindurant** [comment]
(edit, maybe get_event_loop should have worked, actually - but you shouldn't need this line at all)

**Comment by abdallahashraf22** [comment]
Hello @martindurant , I've came across this error today when trying to use this code

```
@app.get("/file")
async def download_file():
    file_path = "some_file_path"
    fs = S3FileSystem(endpoint_url=DO_SPACES_ENDPOINT, key=DO_SPACES_KEY, secret=DO_SPACES_SECRET, asynchronous=True)
    session = await fs.set_session()
    try:
        return StreamingResponse(fs.open(file_path))
    finally:
        session.close()
```

tried to add the loop as 

```
@app.get("/file")
async def download_file():
    file_path = "some_file_path"
    fs = S3FileSystem(endpoint_url=DO_SPACES_ENDPOINT, key=DO_SPACES_KEY, secret=DO_SPACES_SECRET, asynchronous=True, loop=asyncio.get_running_loop())
    session = await fs.set_session()
    try:
        return StreamingResponse(fs.open(file_path))
    finally:
        session.close()
```

still facing the same issue, so I came across this question where you suggested that the removal of those would still work as long as I call it from inside a co-routine

and the final code is 

```
@app.get("/file")
async def download_file():
    file_path = "some_file_path"
    fs = S3FileSystem(endpoint_url=DO_SPACES_ENDPOINT, key=DO_SPACES_KEY, secret=DO_SPACES_SECRET)
    return StreamingResponse(fs.open(file_path))
```

my question here is ... how do I know if it was actually async? 
tried to print the type of fs.open(file_path) and got an `s3fs.core.S3File`, where I would regularly be expecting a coroutine


I also looked at fastapi's implementation of StreamingResponse
the important part being (added the print statements myself)

```
        if isinstance(content, typing.AsyncIterable):
            print("AsyncIterable")
            self.body_iterator = content
        else:
            print("not AsyncIterable")
            self.body_iterator = iterate_in_threadpool(content)
```
and it goes as not AsyncIterable, so the content fetching is ran in threadpool, meaning not async

am I doing something wrong or is this a problem not expected from fastapi's part with how s3fs async functions are added through sync wrappers?

how do I actually know if fs.open(file_path) is running as an async call

**Comment by martindurant** [comment]
The File abstraction is fundamentally synchronous, and you probably don't want to use it at all inside asynchronous code. There is an open_async method you might want to use, but also `_cat_file` to just get the contents in one go (with optional range specified).

**Comment by abdallahashraf22** [comment]
my use case is mostly gonna be allowing the download of files that could go up to 2GBs in size, so I'm looking for a way to asynchronously "do it" / stream it, my current way is getting chunk after chunk using an AsyncIterator, but it's 512kb chunk at a time, so the download looks buggy slow (not to mention the several calls to s3)

would there be anyway to do it better so using s3fs? (sorry if this might be an irrelevant question to the main topic now, if it happens that there's an answer I'll open a new question, answer it for future references, or add it to the docs)

**Comment by martindurant** [comment]
> would there be anyway to do it better so using s3fs?

@abdallahashraf22 :  get_file will download a file of arbitrary size, and you can specify the chunk size.

**Comment by asant-leitha** [comment]
Any update on this? Using glob raises the same error

**Comment by martindurant** [comment]
@asant-leitha : please show what you are doing. The async counterpart to `glob()` is `_glob()`. 

In a followup response to @abdallahashraf22, I realise I don't actually know what you are wanting to achieve - what does it mean to `return` some file-like thing in an API handler endpoint? I notice that you have `finally` clauses that will certainly close the connection on return, before that returned value could be used at all.

**Comment by asant-leitha** [comment]
@martindurant 

My code is

```
session = await self.s3.set_session()

if len(await self.s3._glob(path)) <= 0:
    # LOGGER.debug(f'File not found at the following path: {path}')
    return None
```

And I'm getting the following error

```
self = <aiohttp.connector.TCPConnector object at 0x31e4d7b60>
key = ConnectionKey(host='lths3.servizi.gr-u.it', port=10447, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)
traces = []

    async def _wait_for_available_connection(
        self, key: "ConnectionKey", traces: List["Trace"]
    ) -> None:
        """Wait for an available connection slot."""
        # We loop here because there is a race between
        # the connection limit check and the connection
        # being acquired. If the connection is acquired
        # between the check and the await statement, we
        # need to loop again to check if the connection
        # slot is still available.
        attempts = 0
        while True:
            fut: asyncio.Future[None] = self._loop.create_future()
            keyed_waiters = self._waiters[key]
            keyed_waiters[fut] = None
            if attempts:
                # If we have waited before, we need to move the waiter
                # to the front of the queue as otherwise we might get
                # starved and hit the timeout.
                keyed_waiters.move_to_end(fut, last=False)
    
            try:
                # Traces happen in the try block to ensure that the
                # the waiter is still cleaned up if an exception is raised.
                if traces:
                    for trace in traces:
                        await trace.send_connection_queued_start()
>               await fut
E               asyncio.exceptions.CancelledError

.venv/lib/python3.12/site-packages/aiohttp/connector.py:600: CancelledError
```

**Comment by asant-leitha** [comment]
@martindurant 

After some other tries I am now getting this:

```

Traceback (most recent call last):qdm_handler:24 | backward | pioggia | 1-8101-2024-
  File "/Users/asant/Desktop/lorentz-enrichment/lorentz_enrichment/models/indicators/indicatore.py", line 49, in _assign_time_s3r:24 | 
    with xr.open_dataset(await self.s3.open_async(path)) as ds:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/asant/Desktop/lorentz-enrichment/.venv/lib/python3.12/site-packages/xarray/backends/api.py", line 651, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/asant/Desktop/lorentz-enrichment/.venv/lib/python3.12/site-packages/xarray/backends/plugins.py", line 194, in guess_engine
    raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

```

**Comment by abdallahashraf22** [comment]
>  what does it mean to `return` some file-like thing in an API handler endpoint?

download the file

> I notice that you have `finally` clauses that will certainly close the connection on return, before that returned value could be used at all.

I think the fastAPI behavior was the finally only called after the generator "StreamingResponse" finish, but not sure tbh, it was a while back

the modified code however removed it anyway

```
@app.get("/file")
async def download_file():
    file_path = "some_file_path"
    fs = S3FileSystem(endpoint_url=DO_SPACES_ENDPOINT, key=DO_SPACES_KEY, secret=DO_SPACES_SECRET)
    return StreamingResponse(fs.open(file_path))
```

but I didn't find it to be async, so it's ran in a threadpool instead of the event loop

I went with another solution, using aioboto3, get a small chunk (512kb) of the file each time, using digitalocean, so the multiple requests don't cost extra, I'm not sure that could be cost effecint in other cloud platforms

**Comment by martindurant** [comment]
```
async def download_file():
    file_path = "some_file_path"
    fs = S3FileSystem(...)
    session = await fs.set_session()
    try:
        return StreamingResponse(fs.open(file_path))
    finally:
        session.close()
```

> I think the fastAPI behavior was the finally only called after the generator "StreamingResponse" finish, but not sure tbh, it was a while back

No, this is not the case. Instead of a corouting, you would need an asynchronous generator, so something like `async yield from`. That is not actually legal syntax (yet?), needing so maybe
```
async for data in StreamingResponse(fs.open(file_path)):
    yield data
```
which would indeed only execute the `finally` clause when the data was exhausted.

**Comment by martindurant** [comment]
but the file-like API (`fs.open()`) is NOT itself async, and fastAPI only has this procedure assuming at least it is *fast*, which is won't be. You also have `fs.open_async` to really stream the file, so something like
```
async def iterfile(path):
    fs = S3FileSystem(...)
    session = await fs.set_session()
    f = fs.open_async(path)
    while True
        data = await f.read(blocksize)
        if data:
            yield data
        else:
            f.close()
            await session.close()
            break

async def download_file():
    return StreamingResponse(iterfile)
```
