### ISSUE TITLE
API miss on s3fs.walk method

### ISSUE THREAD

**Issue by graydenshand** [fsspec/s3fs#807]
The s3fs API docs document the `walk` method as taking an `on_error` parameter: https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem.walk.

This is in line with the general fsspec API https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.walk

However, it seems that the source for `walk` doesn't named the on_error parameter: https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1972-L1976

The effect is that calling s3fs.walk with `on_error` specified passes that parameter through to `_ls()` which does not accept the parameter and raises an error.

Reproducible example
```
>>> from s3fs import S3FileSystem
>>> fs = S3FileSystem()
>>> fs.walk('s3://my-bucket', on_error='omit')
>>> [entry for entry in fs.walk('s3://beta-test-ingestion', on_error='omit')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/Users/gshand/code/py-beta-common/.venv/lib/python3.8/site-packages/fsspec/spec.py", line 393, in walk
    listing = self.ls(path, detail=True, **kwargs)
  File "/Users/gshand/code/py-beta-common/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/gshand/code/py-beta-common/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 80, in sync
    coro = func(*args, **kwargs)
TypeError: _ls() got an unexpected keyword argument 'on_error'
```

**Comment by martindurant** [comment]
Yes, I agree that on_error should be available for s3fs's bulk operations; perhaps someone has the time to add it?
