### ISSUE TITLE
Change introduced in "Try anon=True if no credentials are supplied or found" broke connection to private S3 compatible storage with custom AioSession and AioDeferredRefreshableCredentials.

### ISSUE THREAD

**Issue by nicornk** [fsspec/s3fs#834]
We are using `AioDeferredRefreshableCredentials` to connect to an S3 Compatible API, which is not working anymore since the change in #823 got released in `2023.12.0`. As a workaround we can pin to `2023.10.0`.

This is how we create the `aiobotocore.session.AioSession()`:
https://github.com/emdgroup/foundry-dev-tools/blob/main/src/foundry_dev_tools/foundry_api_client.py#L2068-L2087

Code to reproduce (you would need access to a Foundry instance)...

```
import fsspec
from foundry_dev_tools import FoundryRestClient

fc = FoundryRestClient()
fs = fsspec.filesystem(protocol="s3", **fc.get_s3fs_storage_options())

bucket_file_path = f"ri.foundry.main.dataset...../test.csv"
```

Fails with "Bad Request" because the `is_anon` flag is True:

```is_anon = s3._client_config.signature_version == botocore.UNSIGNED```

Here is the complete log output:

```
Traceback (most recent call last):
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/s3fs/core.py", line 115, in _error_wrapper
    return await func(*args, **kwargs)
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/aiobotocore/client.py", line 386, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Git/s3fs-issue/main.py", line 16, in <module>
    exists = fs.exists(bucket_file_path)
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/s3fs/core.py", line 1073, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/s3fs/core.py", line 1340, in _info
    out = await self._call_s3(
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/s3fs/core.py", line 362, in _call_s3
    return await _error_wrapper(
  File "/Users/user/mambaforge/envs/s3fs/lib/python3.10/site-packages/s3fs/core.py", line 154, in _error_wrapper
    raise err
OSError: [Errno 22] Bad Request
```

I am not sure if the issue is on our side, in the way we construct the AioSession programmatically, because we are not explicitly setting any Signature Version.

**Comment by BENR0** [comment]
No there is not. My experience with (aio)botocore is very limited and how this is implemented is purely based on what I "puzzled" together. I am very curious why you get the error because the `credential_resolver` gets created with your session so should basically do the same? But it seems that I am missing something. Apart from that obviously there is a unit test missing for that case. 

That said from a first glimpse it seems like your proposed solution could work. Did you have a chance to test if that solves your problem?

**Comment by BENR0** [comment]
All right sounds good. Do you want to make a PR or do you want me to do it? I probably will have time for this on Friday/the weekend at the earliest.

**Comment by nicornk** [comment]
Closing since it's reverted
