### ISSUE TITLE
calling flush on s3fs fails

### ISSUE THREAD

**Issue by Skylion007** [fsspec/s3fs#859]
Calling `f.flush()` on an S3FS openfile, fails with the following trace:
```
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x7f0790fc8dc0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fsspec/spec.py", line 1954, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/fsspec/spec.py", line 1931, in close
    if not self.forced:
AttributeError: 'S3File' object has no attribute 'forced'
```
Not sure if this error should be opened up with fsspec instead.

**Comment by Skylion007** [comment]
Upon further research, this was caused due to leaving an openfile context when trying to open a file with an unsupported filemode, still though, we should probably try to be a bit better about handling this error.

**Comment by martindurant** [comment]
Ah, so this happens during interpreter shutdown: so the attributes of the S3File got cleaned up before the file object itself. I'm not sure what can be done about it, since it's very unlikely that making the actual call to the server can succeed, so maybe `__del__` should just warn or silently ignore this kind of thing?
