### ISSUE TITLE
'S3File' object has no attribute 'forced'

### ISSUE THREAD

**Issue by digital-idiot** [fsspec/s3fs#925]
Getting the following error when trying to create and write to a file:

Related Original Issue: https://github.com/Toblerity/Fiona/issues/1476#issuecomment-2565417630

```python
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x10788b560>
Traceback (most recent call last):
  File "~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fsspec/spec.py", line 2216, in __del__
    self.close()
  File "~/.micromamba/envs/PyDev/lib/python3.12/site-packages/fsspec/spec.py", line 2177, in close
    if not self.forced:
           ^^^^^^^^^^^
AttributeError: 'S3File' object has no attribute 'forced'
```

---

```python
fsspec.__version__
Out: '2024.12.0'

s3fs.__version__
Out: '2024.12.0'
```

EDIT
---
Turns out `fiona` is using 'wb+' file mode which does not seem to be supported by  'S3File' object.

**Comment by martindurant** [comment]
> Turns out fiona is using 'wb+' file mode which does not seem to be supported by 'S3File' object.

Would you be willing to provide a PR to raise an appropriate exception for this case? Seeking and writing inplace for remote files is not generally possible, uploads are always essentially streamed.

**Comment by digital-idiot** [comment]
> Would you be willing to provide a PR

Yes. I will try to submit a PR in the coming weekend. Hopefully, I will be able to triag how `fiona` instantiating the `fsspec.AbstractBufferedFile` object with `wb+` mode in the first place. Because according to the following, direct instantiation ought to throw exception.

https://github.com/fsspec/filesystem_spec/blob/1d34249f0b043907f86064c274a33454ec670ebe/fsspec/spec.py#L1878-L1879

**Comment by martindurant** [comment]
> direct instantiation ought to throw exception

indeed

**Comment by digital-idiot** [comment]
Closing this for now, doesn't seem like a `fsspec`/`s3fs` issue exactly.

* Relevant disussion: https://github.com/Toblerity/Fiona/discussions/1479
